language: python
services:
- docker
env:
  COMPOSE_VERSION: 1.4.0
  DOCKER_TLS_VERIFY: 1
  DOCKER_HOST: tcp://45.55.39.167:2376
  DOCKER_CERT_PATH: $TRAVIS_BUILD_DIR/docker/certs
before_install:
 - bash .travis/install-certs
 - bash .travis/install-docker-compose
script:
- echo "Hello World"
after_script:
- docker-compose up -d
