db:
  image: mongo
rabbitmq:
  image: rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"
poller:
  build: .
  environment:
    RABBIT_HOST: rabbitmq
    DB_HOST: db
    DB_NAME: dagobert_mdw
  env_file:
    - .secrets/poller.env
  command: bash .docker/poller
  links:
    - db
    - rabbitmq
web:
  build: .
  environment:
    RABBIT_HOST: rabbitmq
    DB_HOST: db
    DB_NAME: dagobert_mdw
    WORKER_IMAGE: node
  env_file:
    - .secrets/web.env
  command: bash .docker/web
  links:
    - db
    - rabbitmq
  ports:
    - "8000:8000"
