db:
  image: mongo
  restart: always
cron:
  build: ./.docker/cron
  restart: always
  env_file:
    - .secrets/cron.env
  links:
    - web
web:
  build: .
  environment:
    DB_HOST: db
    DB_NAME: dabobert_mdw
  env_file:
    - .secrets/web.env
  restart: always
  ports:
    - "8000:8000"
  links:
    - db
